Patricia Manalang- completed css-flexbox exercise.
patriciamanalang/c1022-code-solutions pull request #16
Opened 2022-10-13 05:28 UTC by patriciamanalang

![Screen Shot 2022-10-12 at 9 46 23 PM](https://user-images.githubusercontent.com/109925604/195509314-a27a14bc-2e60-47d8-8e72-963888e8503a.png)
![Screen Shot 2022-10-12 at 10 02 29 PM](https://user-images.githubusercontent.com/109925604/195509319-06a50d6e-f0ea-4b7d-a7a8-cc353c6f2879.png)
![Screen Shot 2022-10-12 at 10 20 59 PM](https://user-images.githubusercontent.com/109925604/195509325-3985cb5b-4dbc-4d6a-a100-cc23f3eed647.png)
![Screen Shot 2022-10-12 at 10 25 10 PM](https://user-images.githubusercontent.com/109925604/195509334-ad4f70ce-0fad-4423-868e-14a77db1bd9a.png)

2022-10-13 15:43 UTC, codingcodymiller requested changes

2022-10-13 15:43 UTC, codingcodymiller commented on css-flexbox/display-flex.html
> +    }
There is no `container` class in use here 🤔

2022-10-13 15:43 UTC, codingcodymiller commented on css-flexbox/flex-wrap.html
> +    }
![image](https://user-images.githubusercontent.com/32880187/195643050-4d14b250-44af-4a43-955c-3e02ffd6dc02.png)

2022-10-14 06:16 UTC, patriciamanalang commented
<img width="1328" alt="Screen Shot 2022-10-13 at 11 16 16 PM" src="https://user-images.githubusercontent.com/109925604/195775705-b762df3b-129b-4428-bdd2-19272a4f9506.png">

2022-10-14 20:49 UTC, codingcodymiller approved these changes

2022-10-15 16:08 UTC, merged