Css layout classes
patriciamanalang/c1022-code-solutions pull request #17
Opened 2022-10-14 01:53 UTC by patriciamanalang

![Screen Shot 2022-10-13 at 6 49 44 PM](https://user-images.githubusercontent.com/109925604/195743916-f238d33f-26c1-42cd-b520-4e474b4182d6.png)

2022-10-14 20:50 UTC, codingcodymiller requested changes

2022-10-14 20:50 UTC, codingcodymiller commented on css-layout-classes/styles.css
> +  flex-basis: calc(100/3);
This should be `100% / 3`, not `100 / 3`

2022-10-15 17:10 UTC, patriciamanalang commented
![Screen Shot 2022-10-15 at 10 10 07 AM](https://user-images.githubusercontent.com/109925604/195999212-df4fadd8-9bbb-45a8-8e08-fe258a47627d.png)

2022-10-17 16:44 UTC, codingcodymiller approved these changes

2022-10-17 17:11 UTC, merged