Patricia Manalang- Completed css-positioning exercise.
patriciamanalang/c1022-code-solutions pull request #19
Opened 2022-10-14 19:14 UTC by patriciamanalang

![Screen Shot 2022-10-14 at 11 44 07 AM](https://user-images.githubusercontent.com/109925604/195923565-8d7cbd9e-34fa-4298-96d3-1b0c029a0714.png)
![Screen Shot 2022-10-14 at 12 05 26 PM](https://user-images.githubusercontent.com/109925604/195923573-f4873ab7-44b4-49c7-b83d-8d4133dfd694.png)
![Kapture 2022-10-14 at 12 10 52](https://user-images.githubusercontent.com/109925604/195923589-2470f6f4-f795-4829-8bef-121b5c17fc69.gif)

2022-10-14 20:59 UTC, codingcodymiller requested changes

2022-10-14 20:59 UTC, codingcodymiller commented on css-positioning/absolute.css
> +  /* your code here */
If you make this `position: relative`....

2022-10-14 20:59 UTC, codingcodymiller commented on css-positioning/absolute.css
> +}
You won't need this rule.

2022-10-15 20:40 UTC, patriciamanalang commented
![Screen Shot 2022-10-15 at 1 39 28 PM](https://user-images.githubusercontent.com/109925604/196006678-1c0cde04-de00-40b0-9d18-9a4baa8b65c6.png)

2022-10-17 16:45 UTC, codingcodymiller approved these changes

2022-10-17 17:11 UTC, merged