Patricia Manalang - completed css-four-column-layout exercise.
patriciamanalang/c1022-code-solutions pull request #26
Opened 2022-10-18 04:37 UTC by patriciamanalang

<img width="1273" alt="Screen Shot 2022-10-17 at 9 34 45 PM" src="https://user-images.githubusercontent.com/109925604/196336574-1c703686-b3e4-4ca4-a8da-2d9b8ff2b145.png">

2022-10-18 16:26 UTC, codingcodymiller requested changes

2022-10-18 16:26 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +  padding-bottom: 13px;
Only `margin` and `max-width` on the container, class, please shift these declarations to another class.

2022-10-19 03:59 UTC, patriciamanalang commented
<img width="1044" alt="Screen Shot 2022-10-18 at 8 59 08 PM" src="https://user-images.githubusercontent.com/109925604/196594456-eef323c3-3ec0-483d-86cf-1a2d100b1656.png">

2022-10-19 16:20 UTC, codingcodymiller requested changes

2022-10-19 16:20 UTC, codingcodymiller commented on css-four-column-layout/styles.css
> +  padding-bottom: 13px;
Only `flex-basis` should be applied to `column-` classes. Make another class that you can add to the element in addition to the `column-one-fourth` class.

2022-10-20 07:28 UTC, patriciamanalang commented
![Screen Shot 2022-10-20 at 12 27 44 AM](https://user-images.githubusercontent.com/109925604/196883951-ca73d0c3-0ded-4e0d-a3a2-e7593d966749.png)

2022-10-20 18:43 UTC, codingcodymiller approved these changes

2022-10-21 05:54 UTC, merged