Patricia Manalang- Completed html-forms exercise.
patriciamanalang/c1022-code-solutions pull request #7
Opened 2022-10-11 18:38 UTC by patriciamanalang

<img width="815" alt="Screen Shot 2022-10-11 at 11 34 53 AM" src="https://user-images.githubusercontent.com/109925604/195172645-fa76011e-fdf8-492b-b66c-3d675789725a.png">

2022-10-11 21:55 UTC, codingcodymiller requested changes
Hey Patricia! You should have all of your form controls inside one `html` element, not a separate one for each form control

2022-10-11 23:58 UTC, patriciamanalang commented
<img width="613" alt="Screen Shot 2022-10-11 at 4 58 07 PM" src="https://user-images.githubusercontent.com/109925604/195219407-4d209e2f-f8e9-4553-8aad-8544c798bc73.png">

2022-10-12 17:10 UTC, codingcodymiller requested changes
Hey Patricia, you are missing all `label` elements, please revise to include labels where necessary.

2022-10-13 01:12 UTC, patriciamanalang commented
<img width="412" alt="Screen Shot 2022-10-12 at 6 12 35 PM" src="https://user-images.githubusercontent.com/109925604/195476116-1f338fea-c127-472e-81b1-23a44b3507fb.png">

2022-10-13 15:41 UTC, codingcodymiller requested changes
You should re-read the documentation on `label` elements 🤓

2022-10-13 15:41 UTC, codingcodymiller commented on html-forms/index.html
> +    </div>
This should be a `label`

2022-10-13 15:41 UTC, codingcodymiller commented on html-forms/index.html
> +      <input type="radio" name="languages" value="JavaScript"/>Javascript
The text next to each of these should be a `label`

2022-10-13 15:41 UTC, codingcodymiller commented on html-forms/index.html
> +      <input type="checkbox" name="Sign up" value="Sign me up!"/>Sign me up!
"Sign me up!" should be a `label`

2022-10-13 15:41 UTC, codingcodymiller commented on html-forms/index.html
> +    <div>Comments</div>
This should be a `label`

2022-10-13 15:41 UTC, codingcodymiller commented on html-forms/index.html
> +      <label>
There is no text labeling this button, so no `label` element is necessary

2022-10-14 05:39 UTC, patriciamanalang commented
![Screen Shot 2022-10-13 at 10 38 40 PM](https://user-images.githubusercontent.com/109925604/195770523-5cf1fbc4-96b6-40d0-9eef-8e7da9beac7b.png)

2022-10-14 20:48 UTC, codingcodymiller requested changes

2022-10-14 20:48 UTC, codingcodymiller commented on html-forms/index.html
> +      <input type="checkbox" name="Sign up" value="Sign me up!">
This needs an `id` attribute to pair with the `for` attribute on its `label`

2022-10-14 20:48 UTC, codingcodymiller commented on html-forms/index.html
> +    <select name="Select an option">
This needs an `id` attribute to pair with the `for` attribute on its `label`

2022-10-17 16:42 UTC, codingcodymiller approved these changes

2022-10-17 17:10 UTC, merged